homework10/homework10/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

homework10/quotes/urls.py
from django.urls import path
from  . import views

app_name = 'quotes'

urlpatterns = [
    path("", views.main, name='main'),
    path("<int:page>", views.main, name='root_paginate'),
    path('tag/', views.add_tag, name='add_tag'),
    path('note/', views.add_quote, name='add_quote'),
    path('author/', views.add_author, name='add_author'),

]

homework10/users/urls.py
    #path("", views.main, name='root'),


from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logout_view, name='logout'),
    ]

homework10/quotes/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField()
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    #created_at = models.DateTimeField()

    def __str__(self):
        return f"{self.fullname}"

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)



class Quotes(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    quote = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quote}"

homework10/users/models.py
from django.db import models

# Create your models here.

homework10/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, DateInput, DateTimeField, DateTimeInput
from .models import Tag, Quotes, Author

class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    born_date = CharField(min_length=3, max_length=25, required=True, widget=DateInput())
    born_location = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    description = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    #created_at = DateTimeField(input_formats=['%I:%M %p %d-%b-%Y'],
    #                    widget=DateTimeInput(
    #                        attrs={'type': 'datetime-local'},
    #                        format='%I:%M %p %d-%b-%Y'))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']

class QuoteForm(ModelForm):

    quote = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Quotes
        fields = ['quote']
        exclude = ['tags']

homework10/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

homework10/quotes/views.py
from django.contrib.auth import logout
from django.core.mail import message
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .utils import get_mongodb
from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Author

def logout_view(request):
    message.info(request, 'You have logout')
    logout(request)
    return redirect('/')

def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/author.html', {'form': form})

    return render(request, 'quotes/author.html', {'form': AuthorForm()})

def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/tag.html', {'form': form})

    return render(request, 'quotes/tag.html', {'form': TagForm()})

def add_quote(request):
    tags = Tag.objects.all()
    auths = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_note = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            au = Author.objects.get(fullname=request.POST.get('author'))
            au.quotes_set.add(new_note, bulk=False)

            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/note.html', {"tags": tags, "authors": auths, 'form': form})

    return render(request, 'quotes/note.html', {"tags": tags, "authors": auths, 'form': QuoteForm()})

homework10/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm


@login_required
def logout_view(request):
    logout(request)
    return redirect(to='quotes:main')

def loginuser(request):
    if request.user.is_authenticated:
       return redirect(to='quotes:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

homework10/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}

    <div style="padding: 10px">
        <label> author name:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
        <div style="padding: 10px">
        <label> born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
        <div style="padding: 10px">
        <label> description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

homework10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>HomeWork10</title>
</head>
<body>

<div class="container">
    <div class="row header-box pt-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add author</a>
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add quote</a>
                <a href="{% url 'quotes:add_tag' %}" class="btn btn-primary">Add tag</a>
                <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
                {% else %}
                <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                {% endif %}
            </p>
        </div>
    </div>

    {% block content%} {% endblock %}

</div>

</body>
</html>

homework10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords" content="simplicity,understand">
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<nav>
        <ul class="pager">

            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number%} {% else %} # {% endif %}">

                <span aria-hidden="true">←</span> Previous</a>
            </li>


            <li class="next">
                 <a class="{% if not quotes.has_next %} disabled {% endif %}"
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number%} {% else %} # {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>

        </ul>
    </nav>


{% endblock%}

homework10/quotes/templates/quotes/note.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Note quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author" required>
                {% for author in authors %}
                <option value="{{author.fullname}}">"{{author.fullname}}"</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

homework10/quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

homework10/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

homework10/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}